[[patterns]]
pattern = "exmpl-(.*)-sbx-(.*)"
add = "ubuntu@{1}.sbx.example.com"

[[patterns]]
pattern = "(.*).sbx"
add = "ubuntu@{1}.sbx.example.com"

[[patterns]]
pattern = "test--dev"
add = "user@test-{1}"
